# Generated by Django 3.1.7 on 2021-02-24 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberFlat', models.CharField(help_text='Укажите номер квартиры', max_length=10)),
                ('entrance', models.IntegerField(verbose_name='Подъезд')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('square', models.CharField(help_text='Укажите площадь квартиры', max_length=10, verbose_name='Площадь')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название дома', max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=200, verbose_name='Имя')),
                ('fathername', models.CharField(max_length=200, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('docType', models.CharField(blank=True, choices=[('п', 'Паспорт'), ('св', 'Свидетельство о рождении'), ('ин', 'Паспорт иностранного гражданина')], default='п', help_text='Укажите тип документа', max_length=3, verbose_name='Тип документа')),
                ('docSeries', models.CharField(max_length=5, verbose_name='Серия документа')),
                ('docNumber', models.CharField(max_length=8, verbose_name='Номер документа')),
                ('docIssueDate', models.DateField(null=True, verbose_name='Дата выдачи')),
                ('docIssueOrg', models.TextField(verbose_name='Кто выдал')),
                ('owner', models.BooleanField(verbose_name='Собственник')),
                ('ownerPart', models.CharField(choices=[('-', '-'), ('1', 'целая'), ('1/2', 'одна втрорая'), ('1/3', 'одна третья'), ('1/4', 'одна четвертая')], default='-', max_length=200, verbose_name='Часть собственности')),
                ('flat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HouseApp.flat')),
            ],
        ),
        migrations.AddField(
            model_name='flat',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HouseApp.house'),
        ),
    ]
